[package]
name = "ethereum-types"
version = "0.3.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
uint = { path = "../uint", version = "0.2.1", default-features = false }
fixed-hash = { path = "../fixed-hash", version = "0.2" }
ethbloom = { path = "../ethbloom", version = "0.5.0" }
crunchy = "0.1.5"
ethereum-types-serialize = { version = "0.2.1", path = "../serialize", optional = true }
serde = { version = "1.0", optional = true }

[features]
default = ["std", "heapsizeof", "serialize"]
std = ["uint/std", "fixed-hash/std", "ethbloom/std"]
heapsizeof = ["uint/heapsizeof", "fixed-hash/heapsizeof", "ethbloom/heapsizeof"]
serialize = ["std", "ethereum-types-serialize", "serde", "ethbloom/serialize"]
use_asm = ["uint/use_asm"]
impl_quickcheck_arbitrary = ["uint/impl_quickcheck_arbitrary", "fixed-hash/impl_quickcheck_arbitrary"]
alloc = []
